### ISSUE TITLE
Create docs covering all offered features from data

### ISSUE THREAD

**Issue by laissandrade** [wedeploy/docs#14]
https://github.com/cirocosta/hackaday-wedeploy-feedback/issues/42

**Comment by laissandrade** [comment]
Create docs covering all offered features from data
https://github.com/cirocosta/hackaday-wedeploy-feedback/issues/38

**Comment by zenorocha** [comment]
I think we should tackle this once we define the new API Client interface for Data, what do you think?

> Updated issue title.

**Comment by pragmaticivan** [comment]
I update the data structure in sub-sections but still need to have feedback from Eduardo in regards to moving on to the new sugar API proposal.

**Comment by zenorocha** [comment]
Ok, so this is blocked until we create this new sugar API.

**Comment by cirocosta** [comment]
hey, this is done, right? https://github.com/wedeploy/engine/pull/810
