### ISSUE TITLE
What to document on `boilerplate-*` repos

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/docs#25]
Hey,

currently in  the `boilerplate-*` READMEs we're just directing  the user  to `/docs`, but i feel that someone who simply `git clone`s  the  repository might be inclined to stick with `README.md`. Should we document the repositories in their READMEs or let that to `/docs`?  Wdyt?

Thx!

**Comment by igr** [comment]
Im for README, and then copy/paste to `/docs`. In other words: same info on two places.

**Comment by jonnilundy** [comment]
wedeploy/wedeploy.com#158
