### ISSUE TITLE
lowercase `news` in  "subscribe" title

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/docs#31]
Hey,

wdyt about lowercasing the _**N**_ews? Maybe it's a super minor thing but it looks like it's a service, like `WeDeploy News`

![screen shot 2016-09-19 at 9 35 25 pm](https://cloud.githubusercontent.com/assets/3574444/18653574/25586758-7eb1-11e6-9612-05ca4906f76d.png)

**Comment by zenorocha** [comment]
Thanks for the feedback but after talking to @vitorfernandes we think it's better if we keep this one uppercase.

<img width="516" alt="screen shot 2016-09-19 at 5 52 29 pm" src="https://cloud.githubusercontent.com/assets/398893/18653883/e2ebbe5c-7e91-11e6-9840-6a56b2ba0677.png">
