### ISSUE TITLE
Can't load `updating data`

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/docs#32]
![screen shot 2016-09-19 at 9 49 01 pm](https://cloud.githubusercontent.com/assets/3574444/18653848/30a498dc-7eb3-11e6-8c02-76bfee200905.png)

interestingly the `.md` seems to exist:

<img width="659" alt="screen shot 2016-09-19 at 9 51 38 pm" src="https://cloud.githubusercontent.com/assets/3574444/18653861/46d007a4-7eb3-11e6-805b-c062384484de.png">

**Comment by zenorocha** [comment]
Fixed, thanks!
