### ISSUE TITLE
Be explicit about the ports used by `we run`

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/docs#35]

**Comment by henvic** [comment]
Currently the "we run" command already provides feedback if the port is unavailable. Is it really necessary?

**Comment by henvic** [comment]
I mean, at this time / for this milestone, where we don't have yet everything defined. Just want to avoid the docs to be outdated soon, when we decide these things :)

**Comment by jonnilundy** [comment]
@henvic @cirocosta is this issue still active?

**Comment by henvic** [comment]
Closing this abandoned issue as follow-up was never provided.

@cirocosta feel free to reopen it, adding more context, if this is still relevant.

**Comment by jonnilundy** [comment]
If reopen is needed, please do so on the [wedeploy.com](https://github.com/wedeploy/wedeploy.com) repo.
