### ISSUE TITLE
Custom Domains usage

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/docs#38]
Make it clear the better way to use this approach where:

www.mydomain.com is a CNAME to mydomain.com

ivansj.com is an A to wedeploy IP.

the custom domain there is pointing to mydomain.com

The service is called web.

I tried `http://web.mydomain.com` and since I didn't configure web on my domain DNS it is not working. Maybe we need good instructions for this approach.

**Comment by zenorocha** [comment]
Documentation has moved to a new repository (https://github.com/wedeploy/wedeploy.com), if this issue is still valid would you mind moving it over there? Thanks!

**Comment by pragmaticivan** [comment]
Closing because we're moving everything to service level, so not sure if would be a good idea making efforts to write about something that will be outdated.

**Comment by cirocosta** [comment]
👍  Maybe a section about "general concepts"? For instance, `environment variables` is general - applies to all services (even though some of *our*  services have some specific env vars)-?
