### ISSUE TITLE
Add indication of how to configure application on 3rd party provider

### ISSUE THREAD

**Issue by laissandrade** [wedeploy/docs#40]
We need to document which callback url he must add. For example:

`auth.myproject.wedeploy.io/oauth/token`

Or, for local development:

`auth.myproject.wedeploy.me/oauth/token`

**Comment by laissandrade** [comment]
Also add information on how to configure environment variables via dashboard:

<img width="982" alt="screen shot 2016-11-03 at 5 08 13 pm" src="https://cloud.githubusercontent.com/assets/1435318/20008140/24531efc-a27e-11e6-9cdb-651086f7bae8.png">

<img width="984" alt="screen shot 2016-11-04 at 10 59 52 am" src="https://cloud.githubusercontent.com/assets/1435318/20008146/296d8a62-a27e-11e6-9e5a-f54bac5a5a85.png">

<img width="992" alt="screen shot 2016-11-04 at 11 00 49 am" src="https://cloud.githubusercontent.com/assets/1435318/20008152/2ceabade-a27e-11e6-9c86-435fc1c12412.png">

**Comment by zenorocha** [comment]
Yes, we have a plan for that, one page per service type explaining all the env variables and then link to them.
