### ISSUE TITLE
Add Data Type supported WeDeploy Data 

### ISSUE THREAD

**Issue by fabiorogeriosj** [wedeploy/docs#56]
Example: https://docs.mongodb.com/v3.2/reference/bson-types/

**Comment by cirocosta** [comment]
Hey @fabiorogeriosj , could you elaborate more on this?

Thx!

**Comment by henvic** [comment]
Are you talking about content negotiation / accept headers?

**Comment by fabiobenner** [comment]
Hi, I say with regard to the types of data that Service Data supports (String, date, int, float, blob, objectId).

**Comment by jonnilundy** [comment]
wedeploy/wedeploy.com#160
