### ISSUE TITLE
Warn users about docker-for-mac shared folders

### ISSUE THREAD

**Issue by cirocosta** [wedeploy/docs#59]
Hey,

one of our users had trouble trying to `we link` a service that was not within docker-for-mac shared folders set. That's something that could be evicted through documenting the configuration of docker-for-mac more extensively.

Wdyt?
Thx!

**Comment by zenorocha** [comment]
Documentation has moved to a new repository (https://github.com/wedeploy/wedeploy.com), if this issue is still valid would you mind moving it over there? Thanks!

**Comment by jonnilundy** [comment]
wedeploy/wedeploy.com#161
