### ISSUE TITLE
Document WEDEPLOY_WEB_PATH env variable

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/docs#65]
When developing an application, the output is often produced from some build process.
This could be a Gulp/Grunt task and the result is usually in a folder called `out` or `dist`. In this case, `index.html` won't be in the main folder, but in `dist` or `out`.

We have to add to the [documentation](https://github.com/wedeploy/docs/blob/b13c4c48623ad60359f716e970ae7328ac90c5d0/hosting/index.md) information about how to specify where the output result is. This is the purpose of `WEDEPLOY_WEB_PATH` environment variable. Its value specifies where WeDeploy hosting service will look for the files.

**Comment by zenorocha** [comment]
Documentation has moved to a new repository (https://github.com/wedeploy/wedeploy.com), if this issue is still valid would you mind moving it over there? Thanks!
