### ISSUE TITLE
Document that the hosting service provides ETag and gzip OOTB

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/docs#66]
The hosting service provides OOTB some goodies for the developers. These include ETag and gzip compression. The fact that ETag is available would save some work of the developer, because he won't have to add versions to his CSS and JS files to force the browser to reload them when a new version is created.

**Comment by zenorocha** [comment]
Documentation has moved to a new repository (https://github.com/wedeploy/wedeploy.com), if this issue is still valid would you mind moving it over there? Thanks!
