### ISSUE TITLE
Document the hooks inside container.json

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/docs#67]
Currently the hooks inside `container.json` are [not documented](https://github.com/wedeploy/docs/blob/b13c4c48623ad60359f716e970ae7328ac90c5d0/intro/configuration-files.md).

We have to document them and describe possible use cases.

**Comment by zenorocha** [comment]
Documentation has moved to a new repository (https://github.com/wedeploy/wedeploy.com), if this issue is still valid would you mind moving it over there? Thanks!
