### ISSUE TITLE
Document protecting path with roles

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/docs#69]
Protecting given path with roles have to be added to the documentation. Here is an example:
```
{
  "data": true,
  "path": "/",
  "auth": {
    "scopes": ["admin"]
  }
}
```

**Comment by zenorocha** [comment]
Documentation has moved to a new repository (https://github.com/wedeploy/wedeploy.com), if this issue is still valid would you mind moving it over there? Thanks!
