### ISSUE TITLE
Document how to protect a collection

### ISSUE THREAD

**Issue by ipeychev** [wedeploy/docs#74]
Docs currently lack information how to protect a collection to be accessed only by authenticated user. 

For example, the following code will forbid anonymous requests to `boards` collection by checking if the field `userId` in the `boards` collection matches the Id of currently authenticated user:
```json
[
  {
    "data": true,
    "path": "/boards",
    "parameters": {
      "filter": {
        "value": {"userId":{"operator":"=","value":"$auth.id"}}
      }
    }
  }
]
```

**Comment by zenorocha** [comment]
Hey @ipeychev,

Documentation has moved to a new repository (https://github.com/wedeploy/wedeploy.com), if this issue is still valid would you mind moving it over there? Thanks!
